language: python
python:
  - "2.6"
  - "2.7"

install:
    - sudo apt-get update
    - sudo apt-get install redis-server -y

    - sudo apt-get install mysql-server python-dev libmysqlclient-dev

    # install python requirements
    - pip install -Ue .[tests] --use-mirrors

script:
    # finally run tests
    - make ci-test
